apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: vitorrrocha/rest-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: rest-api-secret