apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: local/rest-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: GITHUB_TOKEN_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: rest-api-secret
                  key: GITHUB_TOKEN_CREDENTIAL

