name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            repository: medyagh/local-dev-example-with-minikube

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rest-api:latest

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Create Kubernetes Secret
        run: |
         kubectl create secret generic rest-api-secret \
            --from-literal=GITHUB_TOKEN_CREDENTIAL=${{ secrets.TOKEN_CREDENTIAL }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl wait --for=condition=ready pod -l app=rest-api
      - name: Test service URLs
        run: |
          minikube service list
          minikube service rest-api-svc --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service rest-api-svc --url)/version
