name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube
    steps:
    - uses: actions/checkout@v4

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest

    - name: Check cluster status
      run: kubectl get pods -A

    - name: Build Docker image
      run: |
        minikube image build -t local/rest-api:latest .
    
    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic rest-api-secret \
          --from-literal=GITHUB_TOKEN_CREDENTIAL=${{ secrets.TOKEN_CREDENTIAL }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply deployment and service
      run: |
        kubectl apply -f k8s/deployment.yaml

    - name: List services
      run: kubectl get svc

    - name: Check if 'rest-api' service exists
      run: |
        if minikube service list | grep -w "rest-api"; then
          echo "✅ Service 'rest-api' found."
        else
          echo "❌ Service 'rest-api' not found."
          exit 1
        fi