name: Security - Secret Scan

on:
  pull_request:
    branches: [master]


jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install TruffleHog v3
        run: pip install trufflehog

      - name: Run TruffleHog Secret Scan
        run: trufflehog filesystem --directory ./ --no-update