name: Security - Secret Scan

on:
  pull_request:
    branches: [master]

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog secret scan
        run: trufflehog filesystem --directory ./ --no-update